name: Test Project CI/CD
on:
 push:
   branches: [main]
   
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        # Repository name with owner. For example, actions/checkout
        repository: ${{ github.repository }}
    - name: Print Hello World
      run: |
       ls -la
       echo "Hello World"
        

        
   
    
   
 


